apiVersion: v1alpha
kind: xcuitest
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 1
suites:
- name: xcuitest - iPhone 15 Simulator
  app: Apps/DemoApp1.app
  testApp: Apps/DemoApp1UITests-Runner.app
  simulators:
  - name: iPhone 15 Simulator
    platformVersions:
    - "16.0"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
