apiVersion: v1alpha
kind: xcuitest
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 1
suites:
- name: xcuitest - iPhone 15 Simulator
  app: AppsToTest/DemoApp1.zip
  testApp: AppsToTest/DemoApp1UITests-Runner.zip
  simulators:
  - name: iPhone 15 Simulator
    platformVersions:
    - "17.0"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
