apiVersion: v1alpha
kind: xcuitest
showConsoleLog: false
sauce:
  region: us-west-1
  #Set concurrency to 3 if you want 3 parallel simulators  
  concurrency: 1  
  metadata:
    build: RC 1.0.1
    tags:
      - Simulator
      - e2e 
  retries: 3
xcuitest:
  app: AppsToTest-rdc/DemoApp1.ipa
  testApp: AppsToTest-rdc/DemoApp1UITests-Runner.ipa
suites:
- name: xcuitest - Real Device Testing
  timeout: 5m
  shard: concurrency
  testListFile: testListFile.txt
  smartRetry:
    failedOnly: true
  devices:
  - name: "iPhone.*"
    options:
      deviceType: ANY
artifacts:
  cleanup: true
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
