apiVersion: v1alpha
kind: xcuitest
showConsoleLog: false
sauce:
  region: us-west-1
  #Set concurrency to 3 if you want 3 parallel simulators  
  concurrency: 1  
  metadata:
    build: RC 1.0.1
    tags:
      - Simulator
      - e2e 
  retries: 3
xcuitest:
  app: AppsToTest/DemoApp1.zip
  testApp: AppsToTest/DemoApp1UITests-Runner.zip
suites:
- name: xcuitest - iPhone 11 Simulator
  timeout: 5m
  shard: concurrency
  testListFile: testListFile.txt
  smartRetry:
    failedOnly: true
  simulators:
  - name: "iPhone 11 Simulator"
    platformVersions:
    - "16.2"
artifacts:
  cleanup: true
  download:
    match:
    - '*'
    when: always
    directory: ./artifacts
